/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.ide

import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider
import org.xtext.example.mydsl.ide.contentassist.MyDslIdeContentProposalProvider;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
class MyDslIdeModule extends AbstractMyDslIdeModule {

	def Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		MyDslIdeContentProposalProvider
	}
}
